{
 "title": "BeOptimal Copy",
 "time": { "from": "2024-06-18T13:39:43.000Z", "to": "2024-06-18T13:44:16.000Z" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Overall Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "prjperformancetool",
     "rawSql": "SELECT\r\n  test_info.date, test_info.test_result, test_info.client_result, test_info.server_result\r\nFROM\r\nprjperformancetool.test_info\r\nORDER BY test_info.date DESC\r\nLIMIT 1\r\n"
    }
   ]
  },
  {
   "title": "Latest Test ID",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "prjperformancetool",
     "rawSql": "SELECT\r\n  test_info.date, test_info.test_id\r\nFROM\r\nprjperformancetool.test_info\r\nORDER BY test_info.date DESC\r\nLIMIT 1\r\n"
    }
   ]
  },
  {
   "title": "CLIENT: Frametimes during last test",
   "type": "trend",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dataset": "prjperformancetool",
     "rawSql": "SELECT frame_number, test_id, global_frame_time, draw_frame_time, game_frame_time, rhit_frame_time, gpu_frame_time\r\nFROM prjperformancetool.client_metrics"
    },
    {
     "dataset": "prjperformancetool",
     "rawSql": "SELECT date, test_id\r\nFROM prjperformancetool.test_info\r\nORDER BY date DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "SERVER: Frametimes during last test",
   "type": "trend",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dataset": "prjperformancetool",
     "rawSql": "SELECT frame_number, test_id, global_frame_time, game_thread_idle_time, networking_time\r\nFROM prjperformancetool.server_metrics\r\nORDER BY test_id DESC"
    },
    {
     "dataset": "prjperformancetool",
     "rawSql": "SELECT date, test_id\r\nFROM prjperformancetool.test_info\r\nORDER BY date DESC\r\nLIMIT 1"
    }
   ]
  },
  { "title": "Client Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Client Medians",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dataset": "prjperformancetool",
     "rawSql": "SELECT * FROM prjperformancetool.test_info\r\nORDER BY date\r\nLIMIT 100"
    },
    {
     "dataset": "prjperformancetool",
     "rawSql": "SELECT * FROM prjperformancetool.client_pass_fail\r\n"
    }
   ]
  },
  {
   "title": "CLIENT: Last Commit Criteria Pass/Fail",
   "type": "stat",
   "gridPos": { "h": 33, "w": 5, "x": 14, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "prjperformancetool",
     "rawSql": "SELECT\r\n  test_info.date, client_pass_fail.*\r\nFROM\r\nprjperformancetool.test_info\r\nINNER JOIN prjperformancetool.client_pass_fail ON test_info.test_id=client_pass_fail.test_id\r\nORDER BY test_info.date DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "CLIENT: Last Commit Criteria",
   "type": "stat",
   "gridPos": { "h": 33, "w": 4, "x": 19, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "prjperformancetool",
     "rawSql": "SELECT\r\n  test_info.date, client_pass_fail.*\r\nFROM\r\nprjperformancetool.test_info\r\nINNER JOIN prjperformancetool.client_pass_fail ON test_info.test_id=client_pass_fail.test_id\r\nORDER BY test_info.date DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Client 1% Highs",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dataset": "prjperformancetool",
     "rawSql": "SELECT * FROM prjperformancetool.test_info\r\nORDER BY date\r\nLIMIT 100"
    },
    {
     "dataset": "prjperformancetool",
     "rawSql": "SELECT * FROM prjperformancetool.client_pass_fail\r\n"
    }
   ]
  },
  {
   "title": "CLIENT: Last 10 Commits Summary",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dataset": "prjperformancetool",
     "rawSql": "SELECT * FROM prjperformancetool.test_info\r\nORDER BY date DESC\r\nLIMIT 10"
    },
    {
     "dataset": "prjperformancetool",
     "rawSql": "SELECT * FROM prjperformancetool.client_pass_fail\r\n"
    }
   ]
  },
  { "title": "Server Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "SERVER: Last 10 Commits Summary",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dataset": "prjperformancetool",
     "rawSql": "SELECT * FROM prjperformancetool.test_info\r\nORDER BY date DESC\r\nLIMIT 10"
    },
    {
     "dataset": "prjperformancetool",
     "rawSql": "SELECT * FROM prjperformancetool.server_pass_fail\r\n"
    }
   ]
  },
  {
   "title": "SERVER: Last Commit Criteria Pass/Fail",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 14, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "prjperformancetool",
     "rawSql": "SELECT\r\n  test_info.date, server_pass_fail.*\r\nFROM\r\nprjperformancetool.test_info\r\nINNER JOIN prjperformancetool.server_pass_fail ON test_info.test_id=server_pass_fail.test_id\r\nORDER BY test_info.date DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "SERVER: Last Commit Criteria",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 19, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "prjperformancetool",
     "rawSql": "SELECT\r\n  test_info.date, server_pass_fail.*\r\nFROM\r\nprjperformancetool.test_info\r\nINNER JOIN prjperformancetool.server_pass_fail ON test_info.test_id=server_pass_fail.test_id\r\nORDER BY test_info.date DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Server Medians",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dataset": "prjperformancetool",
     "rawSql": "SELECT * FROM prjperformancetool.test_info\r\nORDER BY date\r\nLIMIT 100"
    },
    {
     "dataset": "prjperformancetool",
     "rawSql": "SELECT * FROM prjperformancetool.server_pass_fail\r\n"
    }
   ]
  },
  {
   "title": "Server Highs",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dataset": "prjperformancetool",
     "rawSql": "SELECT * FROM prjperformancetool.test_info\r\nORDER BY date\r\nLIMIT 100"
    },
    {
     "dataset": "prjperformancetool",
     "rawSql": "SELECT * FROM prjperformancetool.server_pass_fail\r\n"
    }
   ]
  }
 ]
}